NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    requirements:
        _locale: "%app.locales%"

sonata_admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /sonata-admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /sonata-admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"

app_api:
    type:     rest
    prefix:   /api
    resource: "@AppBundle/Resources/config/api_routes.yml"

open_api:
    type:     rest
    prefix:   /open_api
    resource: AppBundle\Controller\Api\V1\OpenController

JMSTranslationBundle_ui:
    resource: "@JMSTranslationBundle/Controller/"
    type:     annotation
    prefix:   /_trans