<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ZipCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ZipCodeRepository extends EntityRepository
{
    public function getWrappedList($parent, $items)
    {
        return array(
            'name' => 'zipCode',
            'parent' => $parent,
            'root_parent' => $parent->getRegion(),
            'items' => $items,
            'columns' => 'five'
        );
    }
}
